### ISSUE TITLE
listLazyRoutes

### ISSUE THREAD

**Issue by MistreanuIonutCosmin** [cj-wang/mean-start#1]
immediately after serving the project i get this error.
ERROR in Cannot read property 'listLazyRoutes' of undefined.

P.S: Thank you very much for this repo!

**Comment by dustintheweb** [comment]
Update Angular-CLI to the latest version
https://github.com/angular/angular-cli/issues/3662

**Comment by cj-wang** [comment]
Thanks @dustintheweb. Upgraded cli to beta.24
