### ISSUE TITLE
Unit Tests Fail

### ISSUE THREAD

**Issue by brianmriley** [cj-wang/mean-start#4]
First, solid contribution as I was literally starting to create this basic infrastructure (AJS2 + Node backend with local CI setup for dev) when I ran into your repo -- nice job and much appreciated for sharing.

Second, I ran into some issues running unit tests...

To be safe, I pulled a fresh version this morning (as I had made some changes in my first pull), ran `npm i` followed by dev and all is well in the browser. However, running the unit tests via `ng test` fails. I started to fix them, but wanted to see if you experienced the same. I'm currently running AJS-CLI version >> "angular-cli": "^1.0.0-beta.25.5".

Here's the first error:

`Can't bind to 'ngbCollapse' since it isn't a known property of 'div'. ("and" href="#">MEAN Start</a>`

This is pretty easy to fix by importing NGB and then listing  it as an import for the test bed.

`import { NgbModule } from '@ng-bootstrap/ng-bootstrap';`

and

`TestBed.configureTestingModule({
  imports: [
    RouterTestingModule,
    NgbModule.forRoot(),
  ],
  declarations: [
    AppComponent,
    RouterOutletStubComponent
  ],
  providers: [ {provide: MenuService, useValue: menuServiceMock } ]
});`

You'll also see that I also added the mock service for the injected MenuService in the AppComp, which is the next issue I hit. Finally, the tests for the AppComponent appear to test props that no longer exist on the comp itself...before creating a PR, did you see these as well?

Again, nice work and looking to help you make this setup as robust and enterprise ready as possible.

**Comment by cj-wang** [comment]
Thanks Brian. 
Yes you were right it couldn't pass the unit tests after I updated the navbar with ngb. 
Much appreciated if you could send your PR to fix it. 
Cheers.

**Comment by brianmriley** [comment]
Yup. Will send PR tomorrow if works let's up. Same for e2es. 

Brian Riley
Principal & Technical Architect
Web App Solution, Inc.
c: 617.480.0432

**Comment by cj-wang** [comment]
@brianmriley Thought you were busy so I've updated the testing files, mostly as you had suggested. Can you please review and let me know if I missed anything.  Thanks.

**Comment by brianmriley** [comment]
@cj-wang Yup, work got the best of my, but I'll pull down and give it a run.

**Comment by victorhazbun** [comment]
@brianmriley are you working on a pull request for this issue? If so, when are you gonna submit it? Thanks.
